{{- if and .Values.server.rcon.enabled (not .Values.server.rcon.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hytale.fullname" . }}-rcon
  labels:
    {{- include "hytale.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.server.rcon.password | b64enc | quote }}
{{- end }}
