apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale.fullname" . }}
  labels:
    {{- include "hytale.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: TCP
      name: game
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.port }}
      targetPort: game-udp
      protocol: UDP
      name: game-udp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.server.rcon.enabled }}
    - port: {{ .Values.service.rconPort }}
      targetPort: rcon
      protocol: TCP
      name: rcon
      {{- if and (eq .Values.service.type "NodePort") .Values.service.rconNodePort }}
      nodePort: {{ .Values.service.rconNodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "hytale.selectorLabels" . | nindent 4 }}
