apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale.fullname" . }}
  labels:
    {{- include "hytale.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    # Hytale uses QUIC protocol which runs over UDP
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hytale.selectorLabels" . | nindent 4 }}
